export const statusColour = {
  active: { text: "text-white", bg: "bg-[#2C9958]" },
  approved: { text: "text-white", bg: "bg-[#2C9958]" },
  completed: { text: "text-white", bg: "bg-[#3e9cfb]" },
  pending: { text: "text-white", bg: "bg-[#E2B204]" },
  pre_processing: { text: "text-white", bg: "bg-[#E2B204]" },
  awaiting_approval: { text: "text-white", bg: "bg-[#E2B204]" },
  processing: { text: "text-white", bg: "bg-[#E2B204]" },
  cancelled: { text: "text-white", bg: "bg-[#AD2B19]" },
  rejected: { text: "text-white", bg: "bg-[#AD2B19]" },
  failed: { text: "text-white", bg: "bg-[#AD2B19]" },
  inactive: { text: "text-white", bg: "bg-[#353535]" },
  paused: { text: "text-white", bg: "bg-[#353535]" },
  draft: { text: "text-white", bg: "bg-[#353535]" },
  ready: { text: "text-white", bg: "bg-[#008080]" },
  stopped: { text: "text-white", bg: "bg-[#AD2B19]" },
  scheduled: { text: "text-white", bg: "bg-[#008080]" },
  running: { text: "text-white", bg: "bg-[#2C9958]" },
};
